"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "uz-cyrl" | "ru" | "uz"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  "uz-cyrl": {
    dashboard: "Бошқарув панели",
    home: "Администратор",
    users: "Администратор",
    categories: "Категориялар",
    tags: "Теглар",
    managers: "Раҳбарият",
    articles: "Янгиликлар",
    comments: "Изоҳлар",
    appeals: "Мурожаатлар",
    banners: "Баннерлар",
    settings: "Созламалар",
    logout: "Чиқиш",
    administrator: "Администратор",
    filters: "Филтрлар",
    name: "Номи",
    fullName: "Тўлиқ исми",
    position: "Лавозими",
    phoneNumber: "Телефон рақами",
    bio: "Биография",
    id: "ID",
    apply: "Қўллаш",
    clear: "Тозалаш",
    add: "Қўшиш",
    language: "Тил",
    title: "Сарлавҳа",
    alias: "Тахаллус",
    created: "Яратилган",
    actions: "Амаллар",
    login: "Кириш",
    register: "Рўйхатдан ўтиш",
    email: "Электрон почта",
    password: "Парол",
    confirmPassword: "Паролни тасдиқланг",
    parent: "Ота-она",
    author: "Муаллиф",
    views: "Кўришлар сони",
    image: "Расм",
    category: "Категория",
    darkMode: "Қоронғу режим",
    lightMode: "Ёруғлик режими",
    deleteConfirm: "Ҳақиқатан ҳам ушбу элементни ўчиришни хоҳлайсизми?",
    cancel: "Бекор қилиш",
    delete: "Ўчириш",
    edit: "Таҳрирлаш",
    save: "Сақлаш",
    addTag: "Тег қўшиш",
    addCategory: "Категория қўшиш",
    addUser: "Фойдаланувчи қўшиш",
    addManager: "Раҳбар қўшиш",
    editManager: "Раҳбарни таҳрирлаш",
    addArticle: "Янгилик қўшиш",
    editArticle: "Янгиликни таҳрирлаш",
    nameTranslit: "Исм транслитерацияси",
    descriptionTranslit: "Тавсиф транслитерацияси",
    description: "Тавсиф",
    selectLanguage: "Тилни танланг",
    selectParentCategory: "Ота-она категориясини танланг",
    selectCategory: "Категорияни танланг",
    parentCategory: "Ота-она категорияси",
    poster: "Плакат",
    uploadPoster: "Плакатни юклаш",
    uploadPhoto: "Расмни юклаш",
    uploadAudio: "Аудио юклаш",
    content: "Контент",
    audio: "Аудио",
    saving: "Сақлаш...",
    roles: "Роллар",
    editUser: "Фойдаланувчини таҳрирлаш",
    changePassword: "Паролни ўзгартириш",
    newPassword: "Янги парол",
    rowsPerPage: "Ҳар бир саҳифадаги қаторлар",
    newsType: "Янгилик тури",
    selectNewsType: "Янгилик турини танланг",
    departmentsAndSectors: "Бўлим ва секторлар",
    subordinateOrganizations: "Тасарруфий ташкилотлар",
    regionalCouncils: "Ҳудудий Кенгашлар",
    department: "Бўлим",
    sector: "Сектор",
    organization: "Ташкилот",
    institution: "Муассаса",
    region: "Вилоят",
    address: "Манзил",
    selectType: "Турни танланг",
    all: "Барчаси",
    general: "Умумий",
    notifications: "Билдиришномалар",
    security: "Хавфсизлик",
    appearance: "Кўриниш",
    customizeInterface: "Интерфейсни созлаш",
    theme: "Мавзу",
    light: "Ёруғ",
    dark: "Қоронғу",
    system: "Тизим",
    notificationPreferences: "Билдиришнома созламалари",
    manageNotifications: "Билдиришномаларни бошқариш",
    emailNotifications: "Email хабарномалар",
    pushNotifications: "Push-хабарномалар",
    weeklyDigest: "Ҳафталик дайжест",
    securitySettings: "Хавфсизлик созламалари",
    manageSecuritySettings: "Хавфсизлик параметрларини бошқариш",
    securityAlerts: "Хавфсизлик огоҳлантиришлари",
    twoFactorAuth: "Икки босқичли аутентификация",
    sessionTimeout: "Сессия вақти",
    minutes: "дақиқа",
    activeDevices: "Фаол қурилмалар",
    manageDevices: "Фаол сеансларни бошқариш",
    revoke: "Бекор қилиш",
    saveChanges: "Ўзгаришларни сақлаш",
    chooseLanguage: "Афзал кўрган тилни танланг",
    preferredLanguage: "Афзал кўрилган тил",
    editRegionalCouncil: "Вилоят Кенгашини таҳрирлаш",
    editSubordinateOrganization: "Қарам ташкилотни таҳрирлаш",
    editDepartment: "Бўлимни таҳрирлаш",
    addDepartment: "Бўлим қўшиш",
    addSubordinateOrganization: "Қарам ташкилот қўшиш",
    addRegionalCouncil: "Вилоят Кенгашини қўшиш",
    mainContent: "ОСНОВНОЕ",
    transliteration: "ТРАНСЛИТ",
    contactInfo: "Алоқа маълумотлари",
    reception: "Қабулхона",
    trustPhone: "Ишонч телефони",
    email: "Электрон почта",
    address: "Манзил",
    value: "Қиймат",
    description: "Тавсиф",
    socialMedia: "Ижтимоий тармоқлар",
    platform: "Платформа",
    url: "URL манзил",
    status: "Ҳолат",
    active: "Фаол",
    inactive: "Фаол эмас",
    selectStatus: "Ҳолатни танланг",
    selectPlatform: "Платформани танланг",
    addSocialMedia: "Ижтимоий тармоқ қўшиш",
    editSocialMedia: "Ижтимоий тармоқни таҳрирлаш",
    addContactInfo: "Алоқа маълумотини қўшиш",
    editContactInfo: "Алоқа маълумотини таҳрирлаш",
    maps: "Хариталар",
    manageMaps: "Хариталарни бошқариш",
    preview: "Олдиндан кўриш",
    lastUpdated: "Сўнгги янгиланиш",
    uploadNew: "Янгисини юклаш",
    editDetails: "Тафсилотларни таҳрирлаш",
    youtubeVideos: "YouTube видеолар",
    addYouTubeVideo: "YouTube видео қўшиш",
    editYouTubeVideo: "YouTube видеони таҳрирлаш",
    youtubeUrl: "YouTube URL манзили",
    youtubeUrlHelp: "YouTube видео URL манзилини киритинг",
    youtubeVideoId: "YouTube видео ID",
    youtubeVideoIdHelp: "YouTube видео ID рақамини киритинг",
    head: "Сарлавҳа",
    type: "Тур",
    news: "Янгиликлар",
    loading: "Юкланмоқда...",
    error: "Хато",
    success: "Муваффақият",
    pleaseCompleteAllRequiredFields: "Барча мажбурий майдонларни тўлдиринг",
    newsAddedSuccessfully: "Янгилик муваффақиятли қўшилди",
    errorAddingNews: "Янгилик қўшишда хатолик юз берди",
    newsUpdatedSuccessfully: "Янгилик муваффақиятли янгиланди",
    errorUpdatingNews: "Янгиликни янгилашда хатолик юз берди",
    newsDeletedSuccessfully: "Янгилик муваффақиятли ўчирилди",
    errorDeletingNews: "Янгиликни ўчиришда хатолик юз берди",
    errorFetchingNews: "Янгиликларни юклашда хатолик юз берди",
    noNewsFound: "Янгиликлар топилмади",
    newsNotFound: "Янгилик топилмади",
    errorLoadingNews: "Янгиликни юклашда хатолик юз берди",
    searchByTitle: "Сарлавҳа бўйича қидириш",
    allCategories: "Барча категориялар",
    allLanguages: "Барча тиллар",
    selectCategory: "Категорияни танланг",
    uploadImages: "Расмларни юклаш",
  },
  ru: {
    dashboard: "Панель управления",
    home: "Администратор",
    users: "Администратор",
    categories: "Категории",
    tags: "Теги",
    managers: "Раҳбарият",
    articles: "Новости",
    comments: "Комментарии",
    appeals: "Обращения",
    banners: "Баннеры",
    settings: "Настройки",
    logout: "Выход",
    administrator: "Администратор",
    filters: "Фильтры",
    name: "Наименование",
    fullName: "Полное имя",
    position: "Должность",
    phoneNumber: "Номер телефона",
    bio: "Биография",
    id: "ID",
    apply: "Применить",
    clear: "Очистить",
    add: "Добавить",
    language: "Язык",
    title: "Название",
    alias: "Алиас",
    created: "Создано",
    actions: "Actions",
    login: "Вход",
    register: "Регистрация",
    email: "Эл. почта",
    password: "Пароль",
    confirmPassword: "Подтвердите пароль",
    parent: "Родитель",
    author: "Автор",
    views: "Кол-во просмотров",
    image: "Изображение",
    category: "Категория",
    darkMode: "Темный режим",
    lightMode: "Светлый режим",
    deleteConfirm: "Вы уверены, что хотите удалить этот элемент?",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    save: "Сохранить",
    addTag: "Добавить тег",
    addCategory: "Добавить категорию",
    addUser: "Добавить пользователя",
    addManager: "Добавить руководителя",
    editManager: "Редактировать руководителя",
    addArticle: "Добавить новость",
    editArticle: "Редактировать новость",
    nameTranslit: "Транслитерация имени",
    descriptionTranslit: "Транслитерация описания",
    description: "Описание",
    selectLanguage: "Выберите язык",
    selectParentCategory: "Выберите родительскую категорию",
    selectCategory: "Выберите категорию",
    parentCategory: "Родительская категория",
    poster: "Постер",
    uploadPoster: "Загрузить постер",
    uploadPhoto: "Загрузить фото",
    uploadAudio: "Загрузить аудио",
    content: "Содержание",
    audio: "Аудио",
    saving: "Сохранение...",
    roles: "Роли",
    editUser: "Редактировать пользователя",
    changePassword: "Изменить пароль",
    newPassword: "Новый пароль",
    rowsPerPage: "Строк на странице",
    newsType: "Тип новости",
    selectNewsType: "Выберите тип новости",
    departmentsAndSectors: "Отделы и секторы",
    subordinateOrganizations: "Подведомственные организации",
    regionalCouncils: "Региональные советы",
    department: "Отдел",
    sector: "Сектор",
    organization: "Организация",
    institution: "Учреждение",
    region: "Регион",
    address: "Адрес",
    selectType: "Выберите тип",
    all: "Все",
    general: "Общие",
    notifications: "Уведомления",
    security: "Безопасность",
    appearance: "Внешний вид",
    customizeInterface: "Настройте интерфейс",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    system: "Системная",
    notificationPreferences: "Настройки уведомлений",
    manageNotifications: "Управление уведомлениями",
    emailNotifications: "Email уведомления",
    pushNotifications: "Push-уведомления",
    weeklyDigest: "Еженедельный дайджест",
    securitySettings: "Настройки безопасности",
    manageSecuritySettings: "Управление параметрами безопасности",
    securityAlerts: "Оповещения безопасности",
    twoFactorAuth: "Двухфакторная аутентификация",
    sessionTimeout: "Тайм-аут сессии",
    minutes: "минут",
    activeDevices: "Активные устройства",
    manageDevices: "Управление активными сессиями",
    revoke: "Отозвать",
    saveChanges: "Сохранить изменения",
    chooseLanguage: "Выберите предпочитаемый язык",
    preferredLanguage: "Предпочитаемый язык",
    editRegionalCouncil: "Редактировать Областной совет",
    editSubordinateOrganization: "Редактировать Подчиненную организацию",
    editDepartment: "Редактировать Отдел",
    addDepartment: "Добавить Отдел",
    addSubordinateOrganization: "Добавить Подчиненную организацию",
    addRegionalCouncil: "Добавить Областной совет",
    mainContent: "ОСНОВНОЕ",
    transliteration: "ТРАНСЛИТ",
    contactInfo: "Контактная информация",
    reception: "Приемная",
    trustPhone: "Телефон доверия",
    email: "Электронная почта",
    address: "Адрес",
    value: "Значение",
    description: "Описание",
    socialMedia: "Социальные сети",
    platform: "Платформа",
    url: "URL адрес",
    status: "Статус",
    active: "Активный",
    inactive: "Неактивный",
    selectStatus: "Выберите статус",
    selectPlatform: "Выберите платформу",
    addSocialMedia: "Добавить социальную сеть",
    editSocialMedia: "Редактировать социальную сеть",
    addContactInfo: "Добавить контактную информацию",
    editContactInfo: "Редактировать контактную информацию",
    maps: "Карты",
    manageMaps: "Управление картами",
    preview: "Предпросмотр",
    lastUpdated: "Последнее обновление",
    uploadNew: "Загрузить новую",
    editDetails: "Редактировать детали",
    youtubeVideos: "YouTube видео",
    addYouTubeVideo: "Добавить YouTube видео",
    editYouTubeVideo: "Редактировать YouTube видео",
    youtubeUrl: "YouTube URL адрес",
    youtubeUrlHelp: "Введите URL адрес YouTube видео",
    youtubeVideoId: "YouTube видео ID",
    youtubeVideoIdHelp: "Введите ID номер YouTube видео",
    head: "Заголовок",
    type: "Тип",
    news: "Новости",
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успех",
    pleaseCompleteAllRequiredFields: "Пожалуйста, заполните все обязательные поля",
    newsAddedSuccessfully: "Новость успешно добавлена",
    errorAddingNews: "Ошибка при добавлении новости",
    newsUpdatedSuccessfully: "Новость успешно обновлена",
    errorUpdatingNews: "Ошибка при обновлении новости",
    newsDeletedSuccessfully: "Новость успешно удалена",
    errorDeletingNews: "Ошибка при удалении новости",
    errorFetchingNews: "Ошибка при загрузке новостей",
    noNewsFound: "Новости не найдены",
    newsNotFound: "Новость не найдена",
    errorLoadingNews: "Ошибка при загрузке новости",
    searchByTitle: "Поиск по названию",
    allCategories: "Все категории",
    allLanguages: "Все языки",
    selectCategory: "Выберите категорию",
    uploadImages: "Загрузить изображения",
  },
  uz: {
    dashboard: "Boshqaruv paneli",
    home: "Administrator",
    users: "Administrator",
    categories: "Kategoriyalar",
    tags: "Teglar",
    managers: "Раҳбарият",
    articles: "Yangiliklar",
    comments: "Izohlar",
    appeals: "Murojaatlar",
    banners: "Bannerlar",
    settings: "Sozlamalar",
    logout: "Chiqish",
    administrator: "Administrator",
    filters: "Filtrlar",
    name: "Nomi",
    fullName: "To'liq ismi",
    position: "Lavozimi",
    phoneNumber: "Telefon raqami",
    bio: "Biografiya",
    id: "ID",
    apply: "Qo'llash",
    clear: "Tozalash",
    add: "Qo'shish",
    language: "Til",
    title: "Sarlavha",
    alias: "Taxallus",
    created: "Yaratilgan",
    actions: "Amallar",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    email: "Elektron pochta",
    password: "Parol",
    confirmPassword: "Parolni tasdiqlang",
    parent: "Ota-ona",
    author: "Muallif",
    views: "Ko'rishlar soni",
    image: "Rasm",
    category: "Kategoriya",
    darkMode: "Qorong'u rejim",
    lightMode: "Yorug'lik rejimi",
    deleteConfirm: "Haqiqatan ham ushbu elementni o'chirishni xohlaysizmi?",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    save: "Saqlash",
    addTag: "Teg qo'shish",
    addCategory: "Kategoriya qo'shish",
    addUser: "Foydalanuvchi qo'shish",
    addManager: "Rahbar qo'shish",
    editManager: "Rahbarni tahrirlash",
    addArticle: "Yangilik qo'shish",
    editArticle: "Yangilikni tahrirlash",
    nameTranslit: "Ism transliteratsiyasi",
    descriptionTranslit: "Tavsif transliteratsiyasi",
    description: "Tavsif",
    selectLanguage: "Tilni tanlang",
    selectParentCategory: "Ota-ona kategoriyasini tanlang",
    selectCategory: "Kategoriyani tanlang",
    parentCategory: "Ota-ona kategoriyasi",
    poster: "Plakat",
    uploadPoster: "Plakatni yuklash",
    uploadPhoto: "Rasmni yuklash",
    uploadAudio: "Audio yuklash",
    content: "Kontent",
    audio: "Audio",
    saving: "Saqlash...",
    roles: "Rollar",
    editUser: "Foydalanuvchini tahrirlash",
    changePassword: "Parolni o'zgartirish",
    newPassword: "Yangi parol",
    rowsPerPage: "Har bir sahifadagi qatorlar",
    newsType: "Yangilik turi",
    selectNewsType: "Yangilik turini tanlang",
    departmentsAndSectors: "Бўлим ва секторлар",
    subordinateOrganizations: "Тасарруфий ташкилотлар",
    regionalCouncils: "Ҳудудий Кенгашлар",
    department: "Бўлим",
    sector: "Сектор",
    organization: "Ташкилот",
    institution: "Муассаса",
    region: "Вилоят",
    address: "Манзил",
    selectType: "Турни танланг",
    all: "Барчаси",
    general: "Umumiy",
    notifications: "Bildirishnomalar",
    security: "Xavfsizlik",
    appearance: "Ko'rinish",
    customizeInterface: "Interfeysni sozlash",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'u",
    system: "Tizim",
    notificationPreferences: "Bildirishnoma sozlamalari",
    manageNotifications: "Bildirishnomalarni boshqarish",
    emailNotifications: "Email xabarnomalar",
    pushNotifications: "Push-xabarnomalar",
    weeklyDigest: "Haftalik dayjest",
    securitySettings: "Xavfsizlik sozlamalari",
    manageSecuritySettings: "Xavfsizlik parametrlarini boshqarish",
    securityAlerts: "Xavfsizlik ogohlantirishlari",
    twoFactorAuth: "Ikki bosqichli autentifikatsiya",
    sessionTimeout: "Sessiya vaqti",
    minutes: "daqiqa",
    activeDevices: "Faol qurilmalar",
    manageDevices: "Faol seanslarni boshqarish",
    revoke: "Bekor qilish",
    saveChanges: "O'zgarishlarni saqlash",
    chooseLanguage: "Afzal ko'rgan tilni tanlang",
    preferredLanguage: "Afzal ko'rilgan til",
    editRegionalCouncil: "Вилоят Кенгашини таҳрирлаш",
    editSubordinateOrganization: "Қарам ташкилотни таҳрирлаш",
    editDepartment: "Бўлимни таҳрирлаш",
    addDepartment: "Бўлим қўшиш",
    addSubordinateOrganization: "Қарам ташкилот қўшиш",
    addRegionalCouncil: "Вилоят Кенгашини қўшиш",
    mainContent: "ОСНОВНОЕ",
    transliteration: "ТРАНСЛИТ",
    contactInfo: "Aloqa ma'lumotlari",
    reception: "Qabulxona",
    trustPhone: "Ishonch telefoni",
    email: "Elektron pochta",
    address: "Manzil",
    value: "Qiymat",
    description: "Tavsif",
    socialMedia: "Ijtimoiy tarmoqlar",
    platform: "Platforma",
    url: "URL manzil",
    status: "Holat",
    active: "Faol",
    inactive: "Faol emas",
    selectStatus: "Holatni tanlang",
    selectPlatform: "Platformani tanlang",
    addSocialMedia: "Ijtimoiy tarmoq qo'shish",
    editSocialMedia: "Ijtimoiy tarmoqni tahrirlash",
    addContactInfo: "Aloqa ma'lumotini qo'shish",
    editContactInfo: "Aloqa ma'lumotini tahrirlash",
    maps: "Xaritalar",
    manageMaps: "Xaritalarni boshqarish",
    preview: "Oldindan ko'rish",
    lastUpdated: "So'nggi yangilanish",
    uploadNew: "Yangisini yuklash",
    editDetails: "Tafsilotlarni tahrirlash",
    youtubeVideos: "YouTube videolar",
    addYouTubeVideo: "YouTube video qo'shish",
    editYouTubeVideo: "YouTube videoni tahrirlash",
    youtubeUrl: "YouTube URL manzili",
    youtubeUrlHelp: "YouTube video URL manzilini kiriting",
    youtubeVideoId: "YouTube video ID",
    youtubeVideoIdHelp: "YouTube video ID raqamini kiriting",
    head: "Sarlavha",
    type: "Tur",
    news: "Yangiliklar",
    loading: "Yuklanmoqda...",
    error: "Xato",
    success: "Muvaffaqiyat",
    pleaseCompleteAllRequiredFields: "Barcha majburiy maydonlarni to'ldiring",
    newsAddedSuccessfully: "Yangilik muvaffaqiyatli qo'shildi",
    errorAddingNews: "Yangilik qo'shishda xatolik yuz berdi",
    newsUpdatedSuccessfully: "Yangilik muvaffaqiyatli yangilandi",
    errorUpdatingNews: "Yangilikni yangilashda xatolik yuz berdi",
    newsDeletedSuccessfully: "Yangilik muvaffaqiyatli o'chirildi",
    errorDeletingNews: "Yangilikni o'chirishda xatolik yuz berdi",
    errorFetchingNews: "Yangiklarni yuklashda xatolik yuz berdi",
    noNewsFound: "Yangiliklar topilmadi",
    newsNotFound: "Yangilik topilmadi",
    errorLoadingNews: "Yangilikni yuklashda xatolik yuz berdi",
    searchByTitle: "Sarlavha bo'yicha qidirish",
    allCategories: "Barcha kategoriyalar",
    allLanguages: "Barcha tillar",
    selectCategory: "Kategoriyani tanlang",
    uploadImages: "Rasmlarni yuklash",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: "ru",
  setLanguage: () => {},
  t: (key) => key,
})

// Update the language options to only include 'uz' and 'ru' as specified
// Remove 'uz-cyrl' option as it's not supported yet
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ru")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["ru", "uz"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string) => {
    // First check if the language exists in translations
    if (!translations[language]) {
      // Fall back to Russian if the current language doesn't exist
      return translations["ru"][key as keyof (typeof translations)["ru"]] || key
    }

    // Then check if the key exists for the language
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
